#distri_info:
#  #Hi, this is a list in YAML
#  integrantes:
#  - name: Christopher Mendoza
#    email: christopher.mendoza@fiuni.edu.py
#    data_list:
#      - 67
#      - 911
#  - name: Noelia Rotela
#    email: noeliarotela@fiuni.edu.py
#    data_list: ["1","2"]
#  - name: Matias Mareco
#    email: matias.marecos@fiuni.edu.py
#    data_list:
#      - Pilar
#    #Multiline string
#    bio: |
#      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et
#      dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex
#      ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat
#      nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit
#      anim id est laborum

spring:
  datasource:
    url: ${DB_URL}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
  liquibase:
    change-log: classpath:db/changelog-master.xml
  config:
    import:
      - optional:file:.env[.properties]
  application:
    name: app-eve-common
    description: Proyecto de Sistemas Distribuidos
    secret: ${SECRET}

    event:
      min_tickets_per_person: 1
      max_tickets_per_person: 10


